version: '3.4'

services:
  weed_training:
    env_file:
      - env.list
    image: training:v2
    container_name: weed_training_download_wasp
    volumes:
      - ./train:/train
      - ./code:/code
      - ./vision:/code/vision
      - ${WEED_DATA_PATH}:/weed_data
      - ./file_lists:/file_lists
    network_mode: "host"
    entrypoint: ["python3", "/code/download_all_weed_data.py", "-f", "/file_lists/weed_wasp.txt", "-r", "/weed_data"]
    restart: "no"