version: '3.4'

services:
  weed_training:
    runtime: nvidia
    shm_size: 4g
    env_file:
      - env.list
    image: training:v2
    container_name: weed_training    
    volumes:
      - ./train:/train
      - ./code:/code
      - ./vision:/code/vision
      - ${WEED_DATA_PATH}:/weed_data
    network_mode: "host"
    entrypoint: ["python3", "/code/test_model.py", "-f", "/code/settings_file_gt_train_val.json", "-m", "/train/resnet18_model.pth", "-p", "/train/pickled_weed/pd_val_full_hd.pkl", "-s", "/train", "-l", "False", "-i", "False"]
