version: '3.4'

services:
  weed_training:
    env_file:
      - env.list
    image: training:v2
    container_name: weed_training    
    volumes:
      - ./train:/train
      - ./code:/code
      - ./vision:/code/vision
      - ${WEED_DATA_PATH}:/weed_data    
    network_mode: "host"
    entrypoint: ["python3", "/code/auto_annotate.py", "--upload_pkl", "True", "-p", $TRAINING_PICKLE_PATH, "--class_map", "default_class_map"]
