version: '3.4'

services:
  weed_training:
    runtime: nvidia
    shm_size: 4g
    env_file:
      - env.list
    image: training:v1
    container_name: weed_training    
    volumes:
      - ./train:/train
      - ./code:/code
      - ./vision:/code/vision      
      - ${WEED_DATA_PATH}:/weed_data    
    network_mode: "host"
    entrypoint: ["python3", "/code/torch_model_runner.py", "-t", "${TRAINING_PICKLE_PATH}", "-v", "${VALIDATION_PICKLE_PATH}", "-m", "True", "--no_training", "True"]
